services:
  - type: web
    name: pdf-translator
    runtime: python
    buildCommand: |
      apt-get install -y tesseract-ocr tesseract-ocr-por poppler-utils
      pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 8000
